server:
  port: 8888
spring:
  application:
    name: configs
  devtools:
    livereload:
      enabled: false
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///Users/Donovan/Documents/Developments/repositories/git-repos/spring-boot-training/config/src/main/resources/configs
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"